#!/bin/bash
set -uo pipefail

SCHEME_NAME="$1"
SCHEME_VERSION="${2}"
CPU_LIMIT=${CPU_LIMIT:-"30"}
DOCKERIMG=${SCHEME_NAME}:head

temp_dir=$(mktemp -d)
mkdir -p logs
mkdir -p results

for pkg in input/*.scm
do
    echo "***** running package $pkg"
    csplit --quiet -f ${temp_dir}/cov -b '%03d.scm' $pkg '/;; TEST/' '{*}'
    p=$(basename $pkg .scm)
    package="("${p%%-*}" "${p#*-}")"
    if [ "$package" = "(scheme base)" ] ;
    then
        pkg=$package
    else
        pkg="(scheme base) $package"
    fi
    echo "(import $pkg)"
    for file in ${temp_dir}/cov*.scm
    do
        if [ -s $file ]; then
            {
                tmpfile=venv/test.scm
                test=$(grep ';; TEST' $file | cut -f 3 -d\  )
                params=$(grep ';; TEST' $file | cut -f 4- -d\  )
                echo "--------------------------------------------------"
                echo "$pkg" "$test" "$params"
                echo "preludes/${SCHEME_NAME}.scm"
                if [ -f preludes/${SCHEME_NAME}.scm ]
                then
                    cat preludes/$SCHEME_NAME.scm >> $tmpfile
                else
                    if [ ! "$pkg" = "(scheme base)" ]; then
                        cat preludes/generic.scm >> $tmpfile
                    fi
                fi
                echo "(import $pkg)" >> $tmpfile
                echo "(define (assert x) (unless x (error \"ERROR assertion failed\")))" >> $tmpfile
                if [ -r postludes/$SCHEME_NAME.scm ]
                then
                    cat postludes/$SCHEME_NAME.scm >> $tmpfile
                fi
                cat $file >> $tmpfile
                status=0
                timeout -f ${CPU_LIMIT} ./venv/bin/scheme-compile $tmpfile || status=1
                timeout -f ${CPU_LIMIT} ./venv/test || status=1
                rm -rf $tmpfile
                rm -rf venv/test
                echo " -> $status"
            } >> logs/$SCHEME_NAME.log 2>&1
            if [ $status == 0 ]; then
                state=OK
            else
                state=ERROR
            fi
            echo "$SCHEME_NAME,$SCHEME_VERSION,$package,$state,$test,$params" | tee -a results/results.csv
        fi
    done
    rm $temp_dir/*.scm
done

#rm -Rf $temp_dir

# Local Variables:
# mode: sh
# End:
