ARG SCHEME=chibi
ARG IMAGE=${SCHEME}:head
FROM schemers/${IMAGE}

RUN apt-get update && apt-get install -y make git ca-certificates
RUN git clone https://codeberg.org/retropikzel/compile-r7rs.git --depth=2
RUN cd compile-r7rs && ./configure && make && make install

WORKDIR /workdir
COPY Makefile .
COPY input input/
COPY coverage .
