name: r7rs-compability-report

on:
  push:
    branches:
      - 'master'
  schedule:
    - cron: "17 4 * * 2"

jobs:
  report:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Report
        run: |
          make SCHEME=gauche test-docker
          ls && make report
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: results
          path: results/*.csv
      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: index.html