name: r7rs-compability-report

on:
  push:
    branches:
      - 'master'
  schedule:
    - cron: "17 4 * * 2"

jobs:
  report:
    runs-on: ubuntu-22.04
    container:
      image: schemers/gauche:head
    steps:
      - uses: actions/cache@v4
          with:
          path: results
            key: results
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup
        run: apt-get update && apt-get install -y make docker.io
      - name: Gauche
        run: make SCHEME=gauche test-docker && ls
      - name: Report
        run: ls && make report
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: results
          path: results/*.csv
      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: index.html